### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by yassshhhh15** [Project-PixelStar/official_devices#50]
### Device you want to apply for

realme GT NEO 3T (spartan)

### Device Tree Sources

https://github.com/yassshhhh15/android_device_realme_spartan
https://github.com/yassshhhh15/proprietary_vendor_realme_spartan
https://github.com/yassshhhh15/android_hardware_oplus
https://github.com/yassshhhh15/android_kernel_realme_sm8250

### Number of ROM's you maintain officially/unofficially

2

### Any Exceptions/special concern?

Nope 

### Telegram username

@yassshhhh_15

### GitHub username

yassshhhh15

**Comment by amritokun** [comment]
- Go through our documentation, especially regarding [maintainers requirements](https://raw.githubusercontent.com/Project-PixelStar/official_devices/refs/heads/14/maintainerreq.md) and our [code of conduct](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_code_of_conduct.md).

And If You Can Push Regular Updates , I will let you in.

**Comment by yassshhhh15** [comment]
Yeah, went through both the conditions & will push the updates monthly.

**Comment by amritokun** [comment]
Contact Me Over Telegram @amritokun
