### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ByteWave1014** [Project-PixelStar/official_devices#73]
### Device you want to apply for

Poco F6 Pro / Redmi K70 (Vermeer)

### Device Tree Sources

https://github.com/Lunark-Projects/android_device_xiaomi_sm8550-common.git branch 14
https://github.com/Lunark-Projects/android_device_xiaomi_vermeer.git branch 14
https://github.com/Lunark-Projects/vendor_xiaomi.git branch 14
https://github.com/Lunark-Projects/device_xiaomi_vermeer-kernel.git branch 14

### Number of ROM's you maintain officially/unofficially

3 including a PixelStar

### Any Exceptions/special concern?

The kernel is prebuilt, because there is no established kernel source for this device

### Telegram username

@ByteWave1014

### GitHub username

https://github.com/ByteWave1014

**Comment by amritokun** [comment]
- Go through our documentation, especially regarding [maintainers requirements](https://raw.githubusercontent.com/Project-PixelStar/official_devices/refs/heads/14/maintainerreq.md) and our [code of conduct](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_code_of_conduct.md).

And If You Can Push Regular Updates ?

**Comment by ByteWave1014** [comment]
yes, yes I can

**Comment by amritokun** [comment]
Okay, As I can See You did Some Contributions Over Device Trees and Reached me about bootloops and All , Those are fixed ?

**Comment by ByteWave1014** [comment]
If I solved everything, the commits are both in the common and in the vendor

**Comment by amritokun** [comment]
Good Enough, Reach Me Over @amritokun in Telegram

**Comment by ByteWave1014** [comment]
Alright

**Comment by amritokun** [comment]
As per Conversation Over Telegram, 
You Application Has Been Approved.

Regards,
@Takixamru 
**On The Behalf Of Project Pixelstar Team**.
