### ISSUE TITLE
Official maintainership for ingres

### ISSUE THREAD

**Issue by ParsaAslaniYC** [Project-PixelStar/official_devices#83]
### Device you want to apply for

Redmi K50G/POCO F4 GT (ingres)

### Device Tree Sources

github.com/Ingres-Centre
everything is here and they are 100% public

### Number of ROM's you maintain officially/unofficially

Zero

### Any Exceptions/special concern?

Nope

### Telegram username

@itzParsaYC

### GitHub username

github.com/ParsaAslaniYC

**Comment by amritokun** [comment]
Bruh forgot https in links , 
Any ways , From How Much Time You Are Building AOPS/Lineage Based Roms ?

**Comment by ParsaAslaniYC** [comment]
4~5 months

**Comment by amritokun** [comment]
Okay

**Comment by amritokun** [comment]
Conatct Me Over Telegram : @amritokun

**Comment by ParsaAslaniYC** [comment]
@Takixamru btw why chatting in gh while theres tg

**Comment by amritokun** [comment]
Hey @ParsaAslaniYC 

As Per Conversation Over Telegram, 
I am Approving Your Application.
Have A Great Day Ahead.

Regards,
@Takixamru
On behalf of The Project-Pixelstar Team
